#!/bin/bash
echo "Attribute.class"
./jvm Exemplos/Attribute.class
echo "ControleRemoto.class"
./jvm Exemplos/ControleRemoto.class
echo "DataStructure$EvenIterator.class"
./jvm Exemplos/DataStructure$EvenIterator.class
echo "DataStructure.class"
./jvm Exemplos/DataStructure.class
echo "DataStructure$Innerclass2.class"
./jvm Exemplos/DataStructure$Innerclass2.class
echo "Entrada.class"
./jvm Exemplos/Entrada.class
echo "ExcepTest.class"
./jvm Exemplos/ExcepTest.class
echo "HelloWorld.class"
./jvm Exemplos/HelloWorld.class
echo "MaxSeconds.class"
./jvm Exemplos/MaxSeconds.class
echo "ModeloSDX.class"
./jvm Exemplos/ModeloSDX.class
echo "ModeloTV001.class"
./jvm Exemplos/ModeloTV001.class
echo "Volcano/Lava.class"
./jvm Exemplos/Volcano/Lava.class 
echo "Volcano/Volcano.class"
./jvm Exemplos/Volcano/Volcano.class
echo "TV.class"
./jvm Exemplos/TV.class
echo "TestVersion.class"
./jvm Exemplos/TestVersion.class
echo "Teste.class"
./jvm Exemplos/Teste.class 
echo "pinheiro.class"
./jvm Exemplos/pinheiro.class
echo "Soft.class"
./jvm Exemplos/Soft.class
