#!/bin/bash
echo "DataStructure.class"
./jvm Exemplos/Outros/DataStructure.class
echo "Entrada.class"
#./jvm Exemplos/Outros/Entrada.class
#echo "ExcepTest.class"
./jvm Exemplos/Outros/ExcepTest.class
echo "HelloWorld.class"
./jvm Exemplos/Outros/HelloWorld.class
echo "Volcano.class"
./jvm Exemplos/Outros/Volcano.class
echo "TestVersion.class"
./jvm Exemplos/Outros/TestVersion.class
echo "Teste.class"
./jvm Exemplos/Outros/Teste.class 
echo "pinheiro.class"
./jvm Exemplos/Outros/pinheiro.class
echo "Soft.class"
./jvm Exemplos/Outros/Soft.class
